# application.yml
spring:
  application:
    name: olivin-scm
  
  # 데이터베이스 설정
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@43.200.176.156:1521:XE  # Oracle DB 연결 정보 (실제 정보로 변경)
    username: olivin  # 실제 DB 사용자명으로 변경
    password: olivin  # 실제 DB 비밀번호로 변경
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

# JWT 설정
jwt:
  secret: olivin-jwt-secret-key-2024-very-long-secret-key-for-security-please-change-in-production-environment
  expiration: 86400000  # 24시간 (밀리초)

# 로깅 설정
logging:
  level:
    com.olivin: DEBUG
    com.olivin.app.auth.mapper: DEBUG
    org.springframework.security: DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 서버 설정
server:
  port: 3049
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---
# 개발 환경 설정
spring:
  config:
    activate:
      on-profile: dev
  
  # 개발용 로깅 레벨
logging:
  level:
    com.olivin: DEBUG
    org.springframework.security: DEBUG

# JWT 개발용 설정 (짧은 만료 시간)
jwt:
  expiration: 3600000  # 1시간


# MyBatis 설정
mybatis:
  mapper-locations: 
  - classpath:mapper/**/*.xml
  type-aliases-package: com.olivin.app
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: warning
    default-executor-type: simple
    default-statement-timeout: 25
    default-fetch-size: 100
    safe-row-bounds-enabled: false
    local-cache-scope: session
    jdbc-type-for-null: other
    lazy-load-trigger-methods: equals,clone,hashCode,toString
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl